# Generated by Django 5.1.2 on 2024-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'brand_master',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
    ]
