# Generated by Django 5.1.2 on 2024-10-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False},
        ),
    ]
